<?php

// Load Nette Framework or autoloader generated by Composer
use Nette\Application\Routers\Route;

require __DIR__ . '/../libs/autoload.php';


$configurator = new \Nette\Configurator();

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
//$configurator->setDebugMode('83.240.6.212');
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
// Overlay config options in debug (~ development mode)
if($configurator->isDebugMode()) {
	$configurator->addConfig(__DIR__ . '/config/config.development.neon');
}

if(!in_array($_SERVER['REMOTE_ADDR'], ['::1', '127.0.0.1'], true)) {
    Route::$defaultFlags = Route::SECURED;
}
// Tuning config with local only settings like passwords etc.
$configurator->addConfig(__DIR__ . '/config/config.local.neon');
$container = $configurator->createContainer();

//$container->router = new Nette\Application\Routers\SimpleRouter('Homepage:default');
return $container;
